import { integer, jsonb, pgTable, real, serial, text, timestamp } from "drizzle-orm/pg-core";

export const preStoreScanSessionsTable = pgTable("pre_store_scan_sessions", {
  id: serial("id").primaryKey(),
  retailer: text("retailer").notNull().default("Costco"),
  selected_stores: jsonb("selected_stores"),
  hunt_type: text("hunt_type").notNull().default("Category Hunt"),
  selected_category: text("selected_category"),
  search_terms: text("search_terms"),
  capture_methods_used: text("capture_methods_used"),
  started_at: text("started_at").notNull(),
  completed_at: text("completed_at"),
  total_items_found: integer("total_items_found").notNull().default(0),
  must_check_count: integer("must_check_count").notNull().default(0),
  check_if_nearby_count: integer("check_if_nearby_count").notNull().default(0),
  watch_count: integer("watch_count").notNull().default(0),
  skip_count: integer("skip_count").notNull().default(0),
  estimated_total_spend: real("estimated_total_spend").notNull().default(0),
  estimated_total_profit: real("estimated_total_profit").notNull().default(0),
  first_store_to_visit: text("first_store_to_visit"),
  second_store_optional: text("second_store_optional"),
  trip_plan_json: jsonb("trip_plan_json"),
  notes: text("notes"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const preStoreScanItemsTable = pgTable("pre_store_scan_items", {
  id: serial("id").primaryKey(),
  pre_store_scan_session_id: integer("pre_store_scan_session_id").notNull(),
  retailer: text("retailer").notNull(),
  store_location: text("store_location").notNull(),
  product_name: text("product_name").notNull(),
  category: text("category"),
  item_number: text("item_number"),
  upc: text("upc"),
  sku: text("sku"),
  dpci: text("dpci"),
  tcin: text("tcin"),
  online_price: real("online_price"),
  in_store_price: real("in_store_price"),
  stock_status: text("stock_status").notNull().default("Unknown"),
  markdown_signal: text("markdown_signal"),
  last_seen_at: text("last_seen_at"),
  data_source: text("data_source").notNull().default("manual"),
  source_confidence: text("source_confidence").notNull().default("medium"),
  ebay_active_median: real("ebay_active_median"),
  ebay_sold_median: real("ebay_sold_median"),
  amazon_reference_price: real("amazon_reference_price"),
  expected_facebook_sale_price: real("expected_facebook_sale_price"),
  estimated_profit: real("estimated_profit").notNull().default(0),
  pre_store_score: integer("pre_store_score").notNull().default(0),
  trip_priority: text("trip_priority").notNull().default("Watch"),
  target_buy_price: real("target_buy_price"),
  max_quantity: text("max_quantity"),
  recommendation: text("recommendation").notNull().default("Watch Only"),
  reason: text("reason"),
  risk_notes: text("risk_notes"),
  checklist_status: text("checklist_status").notNull().default("Not checked"),
  checklist_note: text("checklist_note"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export type PreStoreScanSession = typeof preStoreScanSessionsTable.$inferSelect;
export type PreStoreScanItem = typeof preStoreScanItemsTable.$inferSelect;
